name: Deploy Project        # Tên workflow

on: push                  # Trigger: chạy khi có push

jobs:
  test:                   # Tên job
    runs-on: ubuntu-latest  # Chạy trên máy chủ Ubuntu của GitHub

    steps:
      - name: Get Code    # Bước 1: Tải code về máy chủ
        uses: actions/checkout@v3

      - name: Check Node version
        run: node -v

      - name: Get Node.js  # Bước 2: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Phiên bản Node.js cần cài đặt
      - name: Install Dependencies  # Bước 3: Cài đặt các dependencies
        run: npm ci
      - name: Run Tests  # Bước 4: Chạy các test
        run: npm test
  deploy:       
    needs: test             # Tên job
    runs-on: ubuntu-latest  # Chạy trên máy chủ Ubuntu của GitHub

    steps:
      - name: Get Code    # Bước 1: Tải code về máy chủ
        uses: actions/checkout@v3

      - name: Check Node version
        run: node -v

      - name: Get Node.js  # Bước 2: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Phiên bản Node.js cần cài đặt
      - name: Install Dependencies  # Bước 3: Cài đặt các dependencies
        run: npm ci
      - name: Build prject
        run: npm run build
      - name: Deploy to Firebase Hosting
        run: echo "Deploying to Firebase Hosting..."